"""
adaptive_question_pool.py — 맞춤 금융이해도/취약성 질문 Pool.

현재는 실행 graph에 연결하지 않은 TODO 설계 파일이다.
목표:
  1. CFPB 10문항 전체와 금융이해도 조사 질문을 통제 가능한 Pool로 보관한다.
  2. 향후 Question Selection Agent가 사용자 feature/계산 결과를 보고 Pool에서 5개만 선택한다.
  3. Agent는 질문을 창작하지 않고, 이 Pool의 question_id를 선택한다.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Literal


QuestionSource = Literal[
    "cfpb_fwb_full",
    "current_cashflow_management",
    "retirement_readiness_new",
    "product_understanding",
    "decision_check_behavior",
    "financial_confidence",
    "money_management",
    "emergency_cashflow",
    "retirement_readiness",
    "cashflow_pressure",
    "product_choice",
    "digital_finance",
    "fraud_protection",
    "financial_attitude",
    "digital_security",
    "financial_knowledge",
]

ResponseScale = Literal[
    "cfpb_p1",
    "cfpb_p2",
    "yes_no",
    "multiple_choice",
    "single_choice",
    "multi_select",
    "agreement",
    "likert_7",
    "frequency",
    "confidence",
    "true_false_unknown",
]


@dataclass(frozen=True)
class QuestionPoolItem:
    id: str
    source: QuestionSource
    category: str
    text_ko: str
    text_en: str = ""
    response_scale: ResponseScale = "multiple_choice"
    options: list[str] = field(default_factory=list)
    reverse_coded: bool = False
    vulnerability_targets: list[str] = field(default_factory=list)
    target_context: str = ""
    selection_hints: list[str] = field(default_factory=list)
    scoring_note: str = ""
    dashboard_effect: dict = field(default_factory=dict)


CFPB_P1_OPTIONS = [
    "Completely",
    "Very well",
    "Somewhat",
    "Very little",
    "Not at all",
]

CFPB_P2_OPTIONS = [
    "Always",
    "Often",
    "Sometimes",
    "Rarely",
    "Never",
]


CFPB_10_QUESTIONS: list[QuestionPoolItem] = [
    QuestionPoolItem(
        id="CFPB_01",
        source="cfpb_fwb_full",
        category="financial_wellbeing_control",
        text_en="I could handle a major unexpected expense.",
        text_ko="큰 예상치 못한 지출이 생겨도 감당할 수 있다.",
        response_scale="cfpb_p1",
        options=CFPB_P1_OPTIONS,
        vulnerability_targets=["emergency_resilience", "liquidity_buffer"],
        selection_hints=["low_liquid_assets", "low_survival_months_at_retirement"],
    ),
    QuestionPoolItem(
        id="CFPB_02",
        source="cfpb_fwb_full",
        category="financial_future",
        text_en="I am securing my financial future.",
        text_ko="나는 나의 금융적 미래를 준비하고 있다.",
        response_scale="cfpb_p1",
        options=CFPB_P1_OPTIONS,
        vulnerability_targets=["retirement_confidence", "future_planning"],
        selection_hints=["age_50_plus", "low_pension_replacement_rate", "no_private_pension"],
    ),
    QuestionPoolItem(
        id="CFPB_03",
        source="cfpb_fwb_full",
        category="financial_constraint",
        text_en="Because of my money situation, I feel like I will never have the things I want in life.",
        text_ko="돈 문제 때문에 내가 원하는 삶의 것들을 결코 갖지 못할 것처럼 느낀다.",
        response_scale="cfpb_p1",
        options=CFPB_P1_OPTIONS,
        reverse_coded=True,
        vulnerability_targets=["subjective_financial_constraint"],
        selection_hints=["high_objective_risk", "low_cashflow", "high_anxiety_possible"],
        scoring_note="CFPB official scoring reverse-codes this item.",
    ),
    QuestionPoolItem(
        id="CFPB_04",
        source="cfpb_fwb_full",
        category="money_management_enjoyment",
        text_en="I can enjoy life because of the way I'm managing my money.",
        text_ko="내가 돈을 관리하는 방식 덕분에 삶을 즐길 수 있다.",
        response_scale="cfpb_p1",
        options=CFPB_P1_OPTIONS,
        vulnerability_targets=["money_management_confidence"],
        selection_hints=["unclear_money_management", "multiple_pensions"],
    ),
    QuestionPoolItem(
        id="CFPB_05",
        source="cfpb_fwb_full",
        category="financial_survival",
        text_en="I am just getting by financially.",
        text_ko="나는 금전적으로 겨우 버티고 있다.",
        response_scale="cfpb_p1",
        options=CFPB_P1_OPTIONS,
        reverse_coded=True,
        vulnerability_targets=["subjective_cashflow_pressure"],
        selection_hints=["low_net_cashflow", "shortfall_monthly_positive"],
        scoring_note="CFPB official scoring reverse-codes this item.",
    ),
    QuestionPoolItem(
        id="CFPB_06",
        source="cfpb_fwb_full",
        category="savings_durability",
        text_en="I am concerned that the money I have or will save won't last.",
        text_ko="내가 가진 돈이나 앞으로 모을 돈이 오래가지 않을까 걱정된다.",
        response_scale="cfpb_p1",
        options=CFPB_P1_OPTIONS,
        reverse_coded=True,
        vulnerability_targets=["retirement_anxiety", "asset_duration_anxiety"],
        selection_hints=["low_asset_duration", "income_gap_years_positive", "age_50_plus"],
        scoring_note="CFPB official scoring reverse-codes this item.",
    ),
    QuestionPoolItem(
        id="CFPB_07",
        source="cfpb_fwb_full",
        category="monthly_budget_strain",
        text_en="Giving a gift for a wedding, birthday or other occasion would put a strain on my finances for the month.",
        text_ko="결혼식, 생일 등 특별한 occasion에 선물을 하면 그 달 재정에 부담이 된다.",
        response_scale="cfpb_p2",
        options=CFPB_P2_OPTIONS,
        reverse_coded=True,
        vulnerability_targets=["monthly_budget_fragility"],
        selection_hints=["low_net_cashflow", "high_essential_expense_ratio"],
        scoring_note="CFPB official scoring reverse-codes this item.",
    ),
    QuestionPoolItem(
        id="CFPB_08",
        source="cfpb_fwb_full",
        category="monthly_surplus",
        text_en="I have money left over at the end of the month.",
        text_ko="월말에 돈이 남는다.",
        response_scale="cfpb_p2",
        options=CFPB_P2_OPTIONS,
        vulnerability_targets=["monthly_surplus_awareness"],
        selection_hints=["low_net_cashflow", "cashflow_uncertain"],
    ),
    QuestionPoolItem(
        id="CFPB_09",
        source="cfpb_fwb_full",
        category="financial_management_delay",
        text_en="I am behind with my finances.",
        text_ko="나는 재정관리가 뒤처져 있다.",
        response_scale="cfpb_p2",
        options=CFPB_P2_OPTIONS,
        reverse_coded=True,
        vulnerability_targets=["money_management_delay", "bill_management"],
        selection_hints=["high_dsr", "loan_repayment_burden", "late_payment_risk"],
        scoring_note="CFPB official scoring reverse-codes this item.",
    ),
    QuestionPoolItem(
        id="CFPB_10",
        source="cfpb_fwb_full",
        category="financial_control",
        text_en="My finances control my life.",
        text_ko="내 재정상태가 내 삶을 지배한다.",
        response_scale="cfpb_p2",
        options=CFPB_P2_OPTIONS,
        reverse_coded=True,
        vulnerability_targets=["financial_stress", "subjective_control_loss"],
        selection_hints=["high_objective_risk", "high_subjective_anxiety_possible"],
        scoring_note="CFPB official scoring reverse-codes this item.",
    ),
]


FINANCIAL_LITERACY_QUESTIONS: list[QuestionPoolItem] = [
    QuestionPoolItem(
        id="QF1_A",
        source="money_management",
        category="decision_participation",
        text_ko="귀하는 평소 귀하의 돈에 대한 의사결정을 하십니까?",
        response_scale="yes_no",
        options=["예", "아니오", "가족이나 다른 사람이 주로 결정"],
        vulnerability_targets=["financial_decision_participation", "self_data_understanding"],
        selection_hints=["multiple_pensions", "unclear_product_understanding"],
    ),
    QuestionPoolItem(
        id="QF2_4",
        source="money_management",
        category="bill_and_loan_management",
        text_ko="카드대금, 대출원리금 등 곧 나올 청구서를 놓치지 않도록 메모하거나 관리하고 있습니까?",
        response_scale="yes_no",
        options=["예", "아니오"],
        vulnerability_targets=["bill_management", "delinquency_prevention"],
        selection_hints=["high_dsr", "loan_repayment_burden"],
    ),
    QuestionPoolItem(
        id="QF2_5",
        source="money_management",
        category="digital_spending_tracking",
        text_ko="은행 앱이나 자금관리 도구를 활용하여 지출상황을 파악하고 있습니까?",
        response_scale="yes_no",
        options=["예", "아니오"],
        vulnerability_targets=["digital_finance_capability", "expense_tracking"],
        selection_hints=["low_digital_usage", "cashflow_uncertain"],
    ),
    QuestionPoolItem(
        id="QF9",
        source="retirement_readiness",
        category="retirement_funding_plan",
        text_ko="귀하는 노후/은퇴자금을 어떻게 마련할 계획이십니까? 은퇴자인 경우 노후자금을 어떻게 조달하고 계십니까?",
        response_scale="multiple_choice",
        options=["국민연금", "퇴직연금", "개인연금", "저축한 돈 인출", "계속 근로", "사업체 수입", "잘 모르겠다"],
        vulnerability_targets=["retirement_income_awareness", "reliable_income_understanding"],
        selection_hints=["age_50_plus", "no_private_pension", "multiple_pensions", "income_gap_years_positive"],
    ),
    QuestionPoolItem(
        id="QF13",
        source="retirement_readiness",
        category="income_loss_runway",
        text_ko="오늘 주된 소득원을 잃는다면 돈을 빌리거나 이사하지 않고 얼마나 오래 생활비를 감당할 수 있습니까?",
        response_scale="multiple_choice",
        options=["1주일 미만", "1주일~1개월", "1~3개월", "3~6개월", "6개월 이상"],
        vulnerability_targets=["income_loss_resilience", "cashflow_buffer"],
        selection_hints=["low_liquid_assets", "low_net_cashflow"],
    ),
    QuestionPoolItem(
        id="QF11",
        source="cashflow_pressure",
        category="expense_exceeds_income",
        text_ko="지난 12개월 동안 수입보다 생활비가 더 많이 든 적이 있었습니까?",
        response_scale="yes_no",
        options=["예", "아니오", "잘 모르겠다"],
        vulnerability_targets=["recent_cashflow_pressure"],
        selection_hints=["low_net_cashflow", "shortfall_monthly_positive"],
    ),
    QuestionPoolItem(
        id="QF12",
        source="cashflow_pressure",
        category="deficit_response_method",
        text_ko="가장 최근 수입보다 생활비가 더 많이 들었을 때 부족한 돈을 어떻게 조달하셨습니까?",
        response_scale="multiple_choice",
        options=["예금 인출", "지출 축소", "자산 처분", "부업/추가근로", "정부/가족 도움", "가족/친구 차입", "대출", "현금서비스/대부업", "납부 지연"],
        vulnerability_targets=["deficit_coping_quality", "high_risk_borrowing"],
        selection_hints=["low_net_cashflow", "high_dsr", "cashflow_pressure"],
    ),
    QuestionPoolItem(
        id="QP5",
        source="product_choice",
        category="comparison_behavior",
        text_ko="금융상품을 선택하기 전에 여러 금융기관의 여러 금융상품을 고려했습니까?",
        response_scale="yes_no",
        options=["예", "아니오", "잘 모르겠다"],
        vulnerability_targets=["comparison_behavior", "product_choice_literacy"],
        selection_hints=["multiple_financial_products", "investment_products_present"],
    ),
    QuestionPoolItem(
        id="QP7",
        source="product_choice",
        category="information_source_reliance",
        text_ko="금융상품 선택에 어떤 정보가 가장 큰 영향을 미쳤습니까?",
        response_scale="multiple_choice",
        options=["전문가 비교정보", "가격비교사이트", "독립투자자문", "광고", "가족/지인", "소셜미디어", "금융기관 직원"],
        vulnerability_targets=["information_source_quality", "mis-selling_vulnerability"],
        selection_hints=["investment_products_present", "high_risk_products"],
    ),
    QuestionPoolItem(
        id="QP9_1",
        source="digital_finance",
        category="online_balance_check",
        text_ko="최근 12개월 동안 온라인으로 계좌 잔액 및 거래내역을 확인한 적이 있습니까?",
        response_scale="frequency",
        options=["자주", "가끔", "거의 없음", "전혀 없음"],
        vulnerability_targets=["self_data_checking", "digital_finance_capability"],
        selection_hints=["low_digital_usage", "mydata_unfamiliar"],
    ),
    QuestionPoolItem(
        id="QP9_8",
        source="digital_finance",
        category="account_aggregation_usage",
        text_ko="최근 12개월 동안 계좌정보 통합관리 웹사이트 또는 앱을 사용한 적이 있습니까?",
        response_scale="frequency",
        options=["자주", "가끔", "거의 없음", "전혀 없음"],
        vulnerability_targets=["mydata_familiarity", "digital_finance_capability"],
        selection_hints=["mydata_unfamiliar", "multiple_accounts"],
    ),
    QuestionPoolItem(
        id="QP10_2",
        source="fraud_protection",
        category="phishing_experience",
        text_ko="지난 2년 동안 이메일, 전화, SNS 메시지로 개인 금융정보를 보냈다가 피해를 본 적이 있습니까?",
        response_scale="yes_no",
        options=["예", "아니오", "잘 모르겠다"],
        vulnerability_targets=["phishing_vulnerability", "consumer_protection_need"],
        selection_hints=["older_age", "digital_security_unknown"],
    ),
    QuestionPoolItem(
        id="QP10_10",
        source="fraud_protection",
        category="hacking_or_phishing_loss",
        text_ko="지난 2년 동안 해킹 또는 피싱으로 돈을 잃은 적이 있습니까?",
        response_scale="yes_no",
        options=["예", "아니오", "잘 모르겠다"],
        vulnerability_targets=["fraud_loss_history", "human_review_signal"],
        selection_hints=["older_age", "digital_finance_usage"],
    ),
    QuestionPoolItem(
        id="QS2_7",
        source="financial_attitude",
        category="regulated_provider_check",
        text_ko="온라인 금융상품을 구매하기 전에 공급기관이 규제되는 기관인지 점검하는 편입니까?",
        response_scale="frequency",
        options=["항상", "자주", "가끔", "거의 안 함", "전혀 안 함"],
        vulnerability_targets=["fraud_prevention_behavior", "product_literacy"],
        selection_hints=["investment_products_present", "digital_finance_usage"],
    ),
    QuestionPoolItem(
        id="QS3_7",
        source="financial_attitude",
        category="money_running_out_anxiety",
        text_ko="돈이 바닥날까 봐 걱정하는 편입니까?",
        response_scale="frequency",
        options=["항상", "자주", "가끔", "거의 아님", "전혀 아님"],
        vulnerability_targets=["subjective_financial_anxiety"],
        selection_hints=["objective_risk_low_but_anxiety_possible", "income_gap_years_positive"],
    ),
    QuestionPoolItem(
        id="QS4_1",
        source="digital_security",
        category="public_wifi_security_awareness",
        text_ko="공용 Wi-Fi로 온라인 쇼핑하는 것이 안전하다고 생각합니까?",
        response_scale="true_false_unknown",
        options=["그렇다", "아니다", "잘 모르겠다"],
        vulnerability_targets=["digital_security_awareness"],
        selection_hints=["digital_finance_usage", "older_age"],
    ),
    QuestionPoolItem(
        id="QK5",
        source="financial_knowledge",
        category="simple_interest",
        text_ko="연 2% 확정이자를 주는 비과세 정기예금에 100만 원을 넣으면 1년 뒤 얼마가 됩니까?",
        response_scale="multiple_choice",
        options=["100만 원", "102만 원", "120만 원", "잘 모르겠다"],
        vulnerability_targets=["interest_literacy"],
        selection_hints=["low_financial_knowledge_unknown"],
    ),
    QuestionPoolItem(
        id="QK7_1",
        source="financial_knowledge",
        category="risk_return",
        text_ko="수익률이 높은 투자는 상대적으로 큰 위험을 수반한다.",
        response_scale="true_false_unknown",
        options=["맞다", "틀리다", "잘 모르겠다"],
        vulnerability_targets=["risk_return_literacy"],
        selection_hints=["investment_products_present", "high_risk_products"],
    ),
    QuestionPoolItem(
        id="QK7_3",
        source="financial_knowledge",
        category="diversification",
        text_ko="다양한 주식이나 지분을 구입하면 투자위험을 줄일 수 있다.",
        response_scale="true_false_unknown",
        options=["맞다", "틀리다", "잘 모르겠다"],
        vulnerability_targets=["diversification_literacy"],
        selection_hints=["investment_products_present"],
    ),
    QuestionPoolItem(
        id="QK7_5",
        source="financial_knowledge",
        category="personal_data_targeting",
        text_ko="온라인에 공개한 개인정보가 금융제안 타깃팅에 사용될 수 있다.",
        response_scale="true_false_unknown",
        options=["맞다", "틀리다", "잘 모르겠다"],
        vulnerability_targets=["personal_data_literacy", "digital_fraud_prevention"],
        selection_hints=["digital_finance_usage", "fraud_protection_unknown"],
    ),
]


SERVICE_QUESTION_BANK: list[QuestionPoolItem] = [
    QuestionPoolItem(
        id="CF03",
        source="current_cashflow_management",
        category="money_management_behavior",
        text_ko="본인 또는 가구의 돈 관리를 위해 하고 있는 행동은 무엇인가요?",
        response_scale="multi_select",
        options=[
            "수입·지출 관리 계획을 세움",
            "지출을 기록함",
            "청구서 낼 돈과 생활비를 분리함",
            "예정된 청구서를 기록해 놓침을 방지함",
            "은행앱/가계부앱으로 지출을 확인함",
            "정기지출 자동이체를 설정함",
            "해당 없음",
        ],
        vulnerability_targets=["cashflow_awareness", "expense_tracking"],
        selection_hints=["cashflow_pressure", "cashflow_uncertain", "low_net_cashflow"],
    ),
    QuestionPoolItem(
        id="CF04",
        source="current_cashflow_management",
        category="emergency_expense_capacity",
        text_ko="오늘 월소득만큼 큰 지출이 생기면, 빌리지 않고 낼 수 있나요?",
        response_scale="single_choice",
        options=["예", "아니오", "잘 모르겠다", "해당 없음"],
        vulnerability_targets=["emergency_resilience", "liquidity_buffer"],
        selection_hints=["low_liquid_assets", "low_survival_months_at_retirement"],
    ),
    QuestionPoolItem(
        id="CF05",
        source="current_cashflow_management",
        category="expense_exceeds_income",
        text_ko="최근 12개월 동안 수입이 생활비를 감당하지 못한 적이 있었나요?",
        response_scale="single_choice",
        options=["예", "아니오", "잘 모르겠다"],
        vulnerability_targets=["recent_cashflow_pressure"],
        selection_hints=["low_net_cashflow", "cashflow_pressure"],
    ),
    QuestionPoolItem(
        id="CF07",
        source="current_cashflow_management",
        category="income_loss_runway",
        text_ko="주 소득원이 끊기면 빌리지 않고 얼마나 생활비를 감당할 수 있나요?",
        response_scale="single_choice",
        options=["1주 미만", "1주 이상~1개월 미만", "1개월 이상~3개월 미만", "3개월 이상~6개월 미만", "6개월 이상", "잘 모르겠다"],
        vulnerability_targets=["cashflow_buffer", "income_loss_resilience"],
        selection_hints=["low_liquid_assets", "cashflow_pressure"],
    ),
    QuestionPoolItem(
        id="CF20",
        source="current_cashflow_management",
        category="subjective_cashflow_pressure",
        text_ko="나는 금전적으로 겨우 버티고 있다.",
        response_scale="agreement",
        options=["전혀 나를 설명하지 않는다", "별로 아니다", "보통이다", "어느 정도 그렇다", "완전히 나를 설명한다"],
        vulnerability_targets=["subjective_cashflow_pressure"],
        selection_hints=["low_net_cashflow", "high_objective_risk"],
    ),
    QuestionPoolItem(
        id="CF23",
        source="current_cashflow_management",
        category="monthly_surplus_awareness",
        text_ko="현재 한 달에 자유롭게 쓸 수 있는 돈이 얼마 정도인지 알고 계신가요?",
        response_scale="single_choice",
        options=["정확히 알고 있다", "대략 알고 있다", "월급/연금이 들어오면 감으로 쓴다", "잘 모른다", "가족이 관리한다"],
        vulnerability_targets=["cashflow_awareness"],
        selection_hints=["cashflow_uncertain", "low_net_cashflow"],
    ),
    QuestionPoolItem(
        id="CF24",
        source="current_cashflow_management",
        category="fixed_expense_awareness",
        text_ko="매달 고정적으로 빠져나가는 보험료, 대출상환액, 카드값을 확인하고 계신가요?",
        response_scale="single_choice",
        options=["항목별로 확인한다", "총액 정도만 확인한다", "큰 금액만 확인한다", "거의 확인하지 않는다", "잘 모르겠다"],
        vulnerability_targets=["fixed_expense_awareness", "bill_management"],
        selection_hints=["loan_repayment_burden", "cashflow_pressure", "cashflow_uncertain"],
    ),
    QuestionPoolItem(
        id="CF25",
        source="current_cashflow_management",
        category="debt_reduction_plan",
        text_ko="대출이나 카드 부담이 있다면, 줄이기 위한 계획을 가지고 계신가요?",
        response_scale="single_choice",
        options=["구체적인 상환 계획이 있다", "줄여야 한다고 생각하지만 구체적 계획은 없다", "부담은 있지만 당장 방법을 모르겠다", "아직 크게 신경 쓰지 않는다", "해당 없음"],
        vulnerability_targets=["repayment_plan", "debt_action_readiness"],
        selection_hints=["high_dsr", "loan_repayment_burden"],
    ),
    QuestionPoolItem(
        id="RT06",
        source="retirement_readiness_new",
        category="retirement_anxiety",
        text_ko="내 돈이 오래가지 않을까 걱정된다.",
        response_scale="agreement",
        options=["매우 그렇다", "그렇다", "보통", "아니다", "전혀 아니다"],
        vulnerability_targets=["retirement_anxiety"],
        selection_hints=["income_gap_years_positive", "retirement_shortfall", "low_survival_months_at_retirement"],
    ),
    QuestionPoolItem(
        id="RT08",
        source="retirement_readiness_new",
        category="retirement_savings_calculation",
        text_ko="은퇴를 위해 얼마를 저축해야 하는지 계산해본 적이 있나요?",
        response_scale="single_choice",
        options=["예", "아니오", "잘 모르겠다"],
        vulnerability_targets=["retirement_planning_behavior"],
        selection_hints=["low_pension_replacement_rate", "retirement_shortfall"],
    ),
    QuestionPoolItem(
        id="RT16",
        source="retirement_readiness_new",
        category="pension_timing_awareness",
        text_ko="국민연금, 퇴직연금, 개인연금이 언제부터 얼마 정도 들어오는지 알고 계신가요?",
        response_scale="single_choice",
        options=["금액과 시점을 모두 알고 있다", "대략 알고 있다", "가입 여부는 알지만 금액·시점은 모른다", "어떤 연금이 있는지도 잘 모른다"],
        vulnerability_targets=["retirement_income_awareness", "pension_timeline_understanding"],
        selection_hints=["multiple_pensions", "income_gap_years_positive", "low_pension_replacement_rate"],
    ),
    QuestionPoolItem(
        id="RT18",
        source="retirement_readiness_new",
        category="pension_expense_comparison",
        text_ko="은퇴 후 예상 연금소득과 예상 생활비를 비교해본 적이 있나요?",
        response_scale="single_choice",
        options=["직접 비교해봤다", "대략 생각해봤다", "연금 예상액만 확인했다", "해본 적 없다", "잘 모르겠다"],
        vulnerability_targets=["retirement_gap_awareness"],
        selection_hints=["retirement_shortfall", "low_pension_replacement_rate"],
    ),
    QuestionPoolItem(
        id="RT20",
        source="retirement_readiness_new",
        category="retirement_action",
        text_ko="은퇴 준비를 위해 현재 실제로 하고 있는 행동이 있나요?",
        response_scale="multi_select",
        options=["국민연금 예상액 확인", "퇴직연금/IRP 확인", "개인연금 납입", "생활비 예상", "부채 줄이기", "특별히 없음"],
        vulnerability_targets=["retirement_action_readiness"],
        selection_hints=["age_50_plus", "retirement_shortfall", "no_private_pension"],
    ),
    QuestionPoolItem(
        id="PR11",
        source="product_understanding",
        category="debt_perception",
        text_ko="현재 부채가 너무 많다고 느끼나요?",
        response_scale="likert_7",
        options=["전혀 동의하지 않음", "동의하지 않음", "약간 동의하지 않음", "보통", "약간 동의", "동의", "매우 동의"],
        vulnerability_targets=["debt_stress_perception"],
        selection_hints=["high_dsr", "loan_repayment_burden"],
    ),
    QuestionPoolItem(
        id="PR15",
        source="product_understanding",
        category="loan_condition_understanding",
        text_ko="현재 보유한 대출의 금리, 월 상환액, 만기일, 상환방식을 어느 정도 알고 계신가요?",
        response_scale="single_choice",
        options=["모두 알고 있다", "월 상환액과 만기 정도는 안다", "매달 빠져나가는 금액만 안다", "대출이 있는 건 알지만 조건은 잘 모른다", "가족/직원이 관리해서 잘 모른다"],
        vulnerability_targets=["loan_condition_understanding"],
        selection_hints=["loan_repayment_burden", "high_dsr"],
    ),
    QuestionPoolItem(
        id="PR17",
        source="product_understanding",
        category="card_cost_understanding",
        text_ko="카드값을 갚을 때 일시불, 할부, 리볼빙, 카드론의 차이를 어느 정도 알고 계신가요?",
        response_scale="single_choice",
        options=["차이와 비용을 알고 있다", "대략 알고 있다", "이름은 알지만 비용 차이는 모른다", "잘 모른다", "사용해본 적은 있지만 설명은 어렵다"],
        vulnerability_targets=["card_cost_understanding"],
        selection_hints=["cashflow_pressure", "loan_repayment_burden"],
    ),
    QuestionPoolItem(
        id="PR18",
        source="product_understanding",
        category="insurance_condition_understanding",
        text_ko="현재 가입한 보험의 월 보험료, 납입기간, 해지조건, 주요 보장내용을 어느 정도 알고 계신가요?",
        response_scale="single_choice",
        options=["대부분 알고 있다", "월 보험료와 주요 보장 정도는 안다", "월 보험료만 안다", "가입은 되어 있지만 내용은 잘 모른다", "가족/설계사가 관리해서 잘 모른다"],
        vulnerability_targets=["insurance_condition_understanding"],
        selection_hints=["cashflow_pressure", "multiple_financial_products"],
    ),
    QuestionPoolItem(
        id="DC01",
        source="decision_check_behavior",
        category="comparison_behavior",
        text_ko="최근 금융상품을 선택할 때 어떻게 결정했나요?",
        response_scale="single_choice",
        options=["여러 회사의 여러 선택지를 비교했다", "한 회사 안에서 여러 선택지를 비교했다", "다른 선택지는 고려하지 않았다", "찾아봤지만 다른 선택지가 없었다", "잘 모르겠다"],
        vulnerability_targets=["comparison_behavior"],
        selection_hints=["multiple_financial_products", "investment_products_present"],
    ),
    QuestionPoolItem(
        id="DC11",
        source="decision_check_behavior",
        category="product_decision_style",
        text_ko="금융상품에 가입하기 전 보통 어떻게 결정하시나요?",
        response_scale="single_choice",
        options=["여러 회사의 조건을 비교한다", "같은 회사 안에서 몇 개 비교한다", "주거래 금융회사 상품을 선택한다", "직원/설계사/가족 추천을 따른다", "광고나 문자, 유튜브를 보고 결정한다"],
        vulnerability_targets=["decision_independence", "mis_selling_vulnerability"],
        selection_hints=["multiple_financial_products", "unclear_product_understanding"],
    ),
    QuestionPoolItem(
        id="DC12",
        source="decision_check_behavior",
        category="information_source_quality",
        text_ko="금융상품을 고를 때 가장 많이 참고하는 정보는 무엇인가요?",
        response_scale="single_choice",
        options=["공식 설명서와 여러 회사 비교자료", "금융회사 앱/홈페이지", "직원/설계사 설명", "가족/지인 의견", "유튜브/SNS/광고", "잘 모르겠다"],
        vulnerability_targets=["information_source_quality"],
        selection_hints=["multiple_financial_products", "investment_products_present"],
    ),
    QuestionPoolItem(
        id="DC14",
        source="decision_check_behavior",
        category="condition_confirmation_behavior",
        text_ko="금융상품 설명 중 이해가 안 되는 조건이 있으면 보통 어떻게 하시나요?",
        response_scale="single_choice",
        options=["이해될 때까지 다시 묻고 결정한다", "가족/지인/전문가에게 확인한다", "인터넷으로 찾아본다", "추천한 사람이 괜찮다고 하면 진행한다", "잘 몰라도 필요해 보이면 진행한다"],
        vulnerability_targets=["confirmation_behavior", "condition_understanding"],
        selection_hints=["unclear_product_understanding", "multiple_financial_products"],
    ),
    QuestionPoolItem(
        id="DC15",
        source="decision_check_behavior",
        category="financial_problem_solving",
        text_ko="금융 문제가 생기면 어떻게 해결하는 편인가요?",
        response_scale="single_choice",
        options=["직접 찾아보고 해결한다", "가족/지인에게 먼저 묻는다", "금융회사나 전문가에게 묻는다", "미루는 편이다", "어떻게 해야 할지 모르겠다"],
        vulnerability_targets=["problem_solving_behavior"],
        selection_hints=["cashflow_pressure", "financial_confidence_low"],
    ),
    QuestionPoolItem(
        id="FC01",
        source="financial_confidence",
        category="daily_finance_confidence",
        text_ko="계좌, 신용카드, 체크카드, 지출관리 같은 일상 금융업무를 잘 처리한다고 느끼나요?",
        response_scale="likert_7",
        options=["전혀 동의하지 않음", "동의하지 않음", "약간 동의하지 않음", "보통", "약간 동의", "동의", "매우 동의"],
        vulnerability_targets=["daily_finance_confidence"],
        selection_hints=["financial_confidence_low", "cashflow_uncertain"],
    ),
    QuestionPoolItem(
        id="FC02",
        source="financial_confidence",
        category="financial_knowledge_self_rating",
        text_ko="본인의 전반적인 금융지식 수준을 어떻게 평가하나요?",
        response_scale="likert_7",
        options=["매우 낮음", "낮음", "약간 낮음", "보통", "약간 높음", "높음", "매우 높음"],
        vulnerability_targets=["financial_knowledge_confidence"],
        selection_hints=["low_financial_knowledge_unknown", "unclear_product_understanding"],
    ),
    QuestionPoolItem(
        id="FC03",
        source="financial_confidence",
        category="emergency_fund_confidence",
        text_ko="한 달 안에 긴급자금을 마련할 자신이 있나요?",
        response_scale="single_choice",
        options=["확실히 마련할 수 있다", "아마 마련할 수 있다", "아마 마련하지 못할 것 같다", "확실히 마련하지 못한다", "잘 모르겠다"],
        vulnerability_targets=["emergency_fund_confidence"],
        selection_hints=["low_liquid_assets", "cashflow_pressure"],
    ),
    QuestionPoolItem(
        id="FC04",
        source="financial_confidence",
        category="retirement_plan_confidence",
        text_ko="은퇴를 위한 재무계획을 잘 세웠다고 얼마나 자신하나요?",
        response_scale="single_choice",
        options=["매우 자신 있다", "자신 있는 편이다", "보통이다", "자신 없는 편이다", "전혀 자신 없다", "은퇴계획이 없다", "잘 모르겠다"],
        vulnerability_targets=["retirement_plan_confidence"],
        selection_hints=["retirement_shortfall", "income_gap_years_positive"],
    ),
    QuestionPoolItem(
        id="FC10",
        source="financial_confidence",
        category="financial_management_delay",
        text_ko="나는 재정관리가 뒤처져 있다.",
        response_scale="frequency",
        options=["항상 그렇다", "자주 그렇다", "가끔 그렇다", "거의 그렇지 않다", "전혀 그렇지 않다"],
        vulnerability_targets=["financial_management_delay"],
        selection_hints=["cashflow_pressure", "financial_confidence_low"],
    ),
]


# Active service bank: cashflow/retirement metrics are used as persona context,
# not as direct questionnaire categories.
SERVICE_QUESTION_BANK = [
    QuestionPoolItem(
        id="PU01",
        source="product_understanding",
        category="loan_condition_understanding",
        text_ko="현재 보유한 대출의 금리, 월 상환액, 만기일, 상환방식을 어느 정도 알고 계신가요?",
        response_scale="single_choice",
        options=["모두 알고 있다", "월 상환액과 만기 정도는 안다", "매달 빠져나가는 금액만 안다", "대출이 있는 건 알지만 조건은 잘 모른다", "가족/직원이 관리해서 잘 모른다"],
        vulnerability_targets=["loan_condition_understanding"],
        target_context="loan_condition_understanding",
        selection_hints=["loan_balance_total_positive", "high_dsr", "dsr_retire_high"],
        dashboard_effect={"priority_cards": ["loan_terms"], "reinforced_sections": ["은퇴 후 상환부담"], "summary": "대출 조건 확인 카드와 은퇴 후 상환부담 설명을 강화합니다."},
    ),
    QuestionPoolItem(
        id="PU02",
        source="product_understanding",
        category="loan_decision_knowledge",
        text_ko="대출상품을 확인할 때 가장 먼저 봐야 한다고 생각하는 것은 무엇인가요?",
        response_scale="single_choice",
        options=["월 상환액, 금리, 총이자, 상환방식", "금리", "한도", "승인 가능 여부", "추천 여부", "잘 모르겠다"],
        vulnerability_targets=["loan_decision_knowledge"],
        target_context="loan_decision_knowledge",
        selection_hints=["loan_balance_total_positive"],
        dashboard_effect={"priority_cards": ["loan_checklist"], "reinforced_sections": ["대출 조건 체크리스트"], "summary": "대출 조건 체크리스트를 제공합니다."},
    ),
    QuestionPoolItem(
        id="PU03",
        source="product_understanding",
        category="insurance_contract_understanding",
        text_ko="현재 가입한 보험의 월 보험료, 납입기간, 해지조건, 주요 보장내용을 어느 정도 알고 계신가요?",
        response_scale="single_choice",
        options=["대부분 알고 있다", "월 보험료와 주요 보장 정도는 안다", "월 보험료만 안다", "가입은 되어 있지만 내용은 잘 모른다", "가족/설계사가 관리해서 잘 모른다"],
        vulnerability_targets=["insurance_contract_understanding"],
        target_context="insurance_contract_understanding",
        selection_hints=["insurance_premium_positive", "insurance_burden_retire_high"],
        dashboard_effect={"priority_cards": ["insurance_fixed_expense"], "reinforced_sections": ["보험료 고정지출", "납입기간 확인"], "summary": "보험료 고정지출 카드와 납입기간 확인을 강화합니다."},
    ),
    QuestionPoolItem(
        id="PU04",
        source="product_understanding",
        category="pension_product_understanding",
        text_ko="연금저축이나 IRP를 유지할 때 가장 중요하게 확인해야 할 것은 무엇이라고 생각하시나요?",
        response_scale="single_choice",
        options=["세액공제, 중도해지 불이익, 수령시점, 운용위험", "세액공제 혜택", "수익률", "은행/앱 추천 여부", "잘 모르겠다"],
        vulnerability_targets=["pension_product_understanding"],
        target_context="pension_product_understanding",
        selection_hints=["private_pension_balance_positive", "irp_contribution_positive", "pension_savings_contribution_positive"],
        dashboard_effect={"priority_cards": ["pension_terms"], "reinforced_sections": ["IRP/연금저축 조건", "중도해지 주의"], "summary": "IRP/연금저축 조건과 중도해지 주의를 설명합니다."},
    ),
    QuestionPoolItem(
        id="PU05",
        source="product_understanding",
        category="pension_income_awareness",
        text_ko="국민연금, 퇴직연금, 개인연금이 언제부터 얼마 정도 들어오는지 알고 계신가요?",
        response_scale="single_choice",
        options=["금액과 시점을 모두 알고 있다", "대략 알고 있다", "가입 여부는 알지만 금액·시점은 모른다", "어떤 연금이 있는지도 잘 모른다"],
        vulnerability_targets=["pension_income_awareness"],
        target_context="pension_income_awareness",
        selection_hints=["public_pension_positive", "private_pension_positive", "income_gap_months_positive"],
        dashboard_effect={"priority_cards": ["pension_timeline"], "reinforced_sections": ["연금 수령 타임라인"], "summary": "연금 수령 타임라인 설명 난이도를 조정합니다."},
    ),
    QuestionPoolItem(
        id="PU06",
        source="product_understanding",
        category="product_cashflow_impact_awareness",
        text_ko="현재 보유한 대출·보험·연금 중 은퇴 후 현금흐름에 가장 큰 영향을 줄 것 같은 항목은 무엇이라고 생각하시나요?",
        response_scale="single_choice",
        options=["대출상환액", "보험료", "국민연금", "퇴직연금/IRP/연금저축", "잘 모르겠다"],
        vulnerability_targets=["product_cashflow_impact_awareness"],
        target_context="product_cashflow_impact_awareness",
        selection_hints=["product_complexity_high"],
        dashboard_effect={"priority_cards": ["product_impact_priority"], "reinforced_sections": ["헷갈리는 상품 우선 설명"], "summary": "사용자가 헷갈리는 상품부터 설명합니다."},
    ),
    QuestionPoolItem(
        id="PU07",
        source="product_understanding",
        category="retirement_lump_sum_understanding",
        text_ko="퇴직금이나 퇴직연금을 한 번에 받을지, 나눠 받을지 결정할 때 어떤 점을 확인해야 한다고 생각하시나요?",
        response_scale="single_choice",
        options=["세금, 월 생활비, 연금수령액, 자산소진 가능성", "세금", "당장 필요한 돈", "주변 추천", "잘 모르겠다"],
        vulnerability_targets=["retirement_lump_sum_understanding"],
        target_context="retirement_lump_sum_understanding",
        selection_hints=["retirement_lump_sum_positive", "retirement_lump_sum_large"],
        dashboard_effect={"priority_cards": ["lump_sum_scenario"], "reinforced_sections": ["퇴직금/퇴직수당 활용 시나리오"], "summary": "퇴직금/퇴직수당 활용 시나리오 설명을 강화합니다."},
    ),
    QuestionPoolItem(
        id="PU08",
        source="product_understanding",
        category="pension_contribution_gap_reason",
        text_ko="연금저축, IRP, 개인연금 납입을 중단하거나 줄인 적이 있다면 이유는 무엇인가요?",
        response_scale="single_choice",
        options=["생활비 부담", "상품 이해 부족", "수익률 불만", "돈이 필요해서", "납입 필요성을 못 느껴서", "중단한 적 없음"],
        vulnerability_targets=["pension_contribution_gap_reason"],
        target_context="pension_contribution_gap_reason",
        selection_hints=["low_pension_contribution", "pension_contribution_gap_possible"],
        dashboard_effect={"priority_cards": ["pension_contribution_gap"], "reinforced_sections": ["연금 납입 공백", "행동 체크리스트"], "summary": "연금 납입 공백과 행동 체크리스트를 제공합니다."},
    ),
    QuestionPoolItem(
        id="DC01",
        source="decision_check_behavior",
        category="comparison_behavior",
        text_ko="금융상품에 가입하기 전 보통 어떻게 결정하시나요?",
        response_scale="single_choice",
        options=["여러 회사의 조건을 비교한다", "같은 회사 안에서 몇 개 비교한다", "주거래 금융회사 상품을 선택한다", "직원/설계사/가족 추천을 따른다", "광고나 문자, 유튜브를 보고 결정한다"],
        vulnerability_targets=["comparison_behavior"],
        target_context="comparison_behavior",
        selection_hints=["default_candidate"],
        dashboard_effect={"priority_cards": ["comparison_table"], "reinforced_sections": ["결정 전 확인 카드"], "summary": "비교표 제공 여부와 결정 전 확인 카드를 조정합니다."},
    ),
    QuestionPoolItem(
        id="DC02",
        source="decision_check_behavior",
        category="information_source_quality",
        text_ko="금융상품을 고를 때 가장 많이 참고하는 정보는 무엇인가요?",
        response_scale="single_choice",
        options=["공식 설명서와 여러 회사 비교자료", "금융회사 앱/홈페이지", "직원/설계사 설명", "가족/지인 의견", "유튜브/SNS/광고", "잘 모르겠다"],
        vulnerability_targets=["information_source_quality"],
        target_context="information_source_quality",
        selection_hints=["default_candidate"],
        dashboard_effect={"priority_cards": ["official_source_check"], "reinforced_sections": ["공식자료 확인", "광고/추천 의존 주의"], "summary": "공식자료 확인 안내와 광고/추천 의존 주의를 강화합니다."},
    ),
    QuestionPoolItem(
        id="DC03",
        source="decision_check_behavior",
        category="condition_checking_behavior",
        text_ko="금융상품을 선택할 때 수수료, 해지조건, 위험요소, 약관의 세부조건을 확인하는 편인가요?",
        response_scale="single_choice",
        options=["항상 확인한다", "중요한 상품만 확인한다", "직원이 설명해주면 듣는 정도다", "거의 확인하지 않는다", "무엇을 봐야 할지 모른다"],
        vulnerability_targets=["condition_checking_behavior"],
        target_context="condition_checking_behavior",
        selection_hints=["any_financial_product"],
        dashboard_effect={"priority_cards": ["condition_checklist"], "reinforced_sections": ["조건 확인 체크리스트"], "summary": "조건 확인 체크리스트를 강화합니다."},
    ),
    QuestionPoolItem(
        id="DC04",
        source="decision_check_behavior",
        category="uncertainty_handling",
        text_ko="금융상품 설명 중 이해가 안 되는 조건이 있으면 보통 어떻게 하시나요?",
        response_scale="single_choice",
        options=["이해될 때까지 다시 묻고 결정한다", "가족/지인/전문가에게 확인한다", "인터넷으로 찾아본다", "추천한 사람이 괜찮다고 하면 진행한다", "잘 몰라도 필요해 보이면 진행한다"],
        vulnerability_targets=["uncertainty_handling"],
        target_context="uncertainty_handling",
        selection_hints=["high_value_default"],
        dashboard_effect={"priority_cards": ["decision_guardrail"], "reinforced_sections": ["결정 전 확인형 CTA", "guardrail"], "summary": "결정 전 확인형 CTA와 guardrail을 강화합니다."},
    ),
    QuestionPoolItem(
        id="DC05",
        source="decision_check_behavior",
        category="decision_owner",
        text_ko="금융상품을 주로 누가 관리하나요?",
        response_scale="single_choice",
        options=["본인이 직접 관리한다", "본인이 보되 가족 도움을 받는다", "가족이 주로 관리한다", "금융회사 직원/설계사에게 의존한다", "잘 모르겠다"],
        vulnerability_targets=["decision_owner"],
        target_context="decision_owner",
        selection_hints=["household_size_2_plus", "spouse_income_present", "product_complexity_high"],
        dashboard_effect={"priority_cards": ["shared_summary"], "reinforced_sections": ["가족/상담사용 요약"], "summary": "가족/상담사용 요약 제공 여부를 조정합니다."},
    ),
    QuestionPoolItem(
        id="DC06",
        source="decision_check_behavior",
        category="help_seeking_behavior",
        text_ko="금융 문제가 생기면 어떻게 해결하는 편인가요?",
        response_scale="single_choice",
        options=["직접 찾아보고 해결한다", "가족/지인에게 먼저 묻는다", "금융회사나 전문가에게 묻는다", "미루는 편이다", "어떻게 해야 할지 모르겠다"],
        vulnerability_targets=["help_seeking_behavior"],
        target_context="help_seeking_behavior",
        selection_hints=["cashflow_pressure", "income_gap_months_positive", "high_dsr"],
        dashboard_effect={"priority_cards": ["advisor_connection"], "reinforced_sections": ["상담 연결", "요약 리포트"], "summary": "상담 연결과 요약 리포트를 강화합니다."},
    ),
    QuestionPoolItem(
        id="DC07",
        source="decision_check_behavior",
        category="provider_legitimacy_checking",
        text_ko="온라인이나 앱에서 금융상품을 확인할 때, 제공 금융회사가 공식 금융회사인지 확인하는 편인가요?",
        response_scale="single_choice",
        options=["항상 확인한다", "자주 확인한다", "가끔 확인한다", "거의 확인하지 않는다", "전혀 확인하지 않는다"],
        vulnerability_targets=["provider_legitimacy_checking"],
        target_context="provider_legitimacy_checking",
        selection_hints=["age_50_plus", "digital_vulnerability_possible"],
        dashboard_effect={"priority_cards": ["fraud_prevention"], "reinforced_sections": ["공식 금융회사 확인", "사기 예방"], "summary": "공식 금융회사 확인 안내와 사기 예방 카드를 제공합니다."},
    ),
    QuestionPoolItem(
        id="DC08",
        source="decision_check_behavior",
        category="retirement_shortfall_response_preference",
        text_ko="은퇴 후 생활비가 부족할 경우, 우선 어떤 방식으로 보완할 수 있다고 생각하시나요?",
        response_scale="single_choice",
        options=["지출 조정", "저축 사용", "계속 일하기", "금융자산 일부 사용", "부동산 등 비금융자산 활용", "가족 도움", "대출 활용", "잘 모르겠다"],
        vulnerability_targets=["retirement_shortfall_response_preference"],
        target_context="retirement_shortfall_response_preference",
        selection_hints=["shortfall_monthly_positive", "retirement_total_shortfall_after_assets_positive"],
        dashboard_effect={"priority_cards": ["shortfall_response_scenarios"], "reinforced_sections": ["부족액 대응 시나리오"], "summary": "부족액 대응 시나리오의 우선순위를 조정합니다."},
    ),
    QuestionPoolItem(
        id="DC09",
        source="decision_check_behavior",
        category="lump_sum_management_preference",
        text_ko="퇴직금처럼 큰 금액을 한 번에 받으면 보통 어떻게 관리하는 것이 좋다고 생각하시나요?",
        response_scale="single_choice",
        options=["생활비·비상금·연금성 자산으로 나누어 관리", "예금에 보관", "필요한 곳에 먼저 사용", "가족/지인 추천에 따름", "잘 모르겠다"],
        vulnerability_targets=["lump_sum_management_preference"],
        target_context="lump_sum_management_preference",
        selection_hints=["retirement_lump_sum_positive", "retirement_lump_sum_large"],
        dashboard_effect={"priority_cards": ["lump_sum_management"], "reinforced_sections": ["퇴직금 활용 시나리오", "목돈 관리"], "summary": "퇴직금 활용 시나리오와 목돈 관리 카드를 제공합니다."},
    ),
    QuestionPoolItem(
        id="FC01",
        source="financial_confidence",
        category="financial_self_efficacy",
        text_ko="계좌, 카드, 대출, 지출 확인 같은 일상 금융업무를 잘 처리한다고 느끼나요?",
        response_scale="agreement",
        options=["매우 동의", "동의", "약간 동의", "보통", "약간 동의하지 않음", "동의하지 않음", "전혀 동의하지 않음"],
        vulnerability_targets=["financial_self_efficacy"],
        target_context="financial_self_efficacy",
        selection_hints=["default_candidate"],
        dashboard_effect={"priority_cards": ["step_by_step_guidance"], "reinforced_sections": ["설명 난이도", "단계별 안내"], "summary": "설명 난이도와 단계별 안내를 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC02",
        source="financial_confidence",
        category="self_rated_financial_knowledge",
        text_ko="본인의 전반적인 금융지식 수준을 어떻게 평가하나요?",
        response_scale="likert_7",
        options=["매우 낮음", "낮음", "약간 낮음", "보통", "약간 높음", "높음", "매우 높음"],
        vulnerability_targets=["self_rated_financial_knowledge"],
        target_context="self_rated_financial_knowledge",
        selection_hints=["default_candidate"],
        dashboard_effect={"priority_cards": ["plain_terms"], "reinforced_sections": ["용어 풀이", "쉬운 설명"], "summary": "용어 풀이와 쉬운 설명 여부를 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC03",
        source="financial_confidence",
        category="retirement_planning_confidence",
        text_ko="은퇴를 위한 재무계획을 잘 세웠다고 얼마나 자신하나요?",
        response_scale="single_choice",
        options=["매우 자신 있다", "자신 있는 편이다", "보통이다", "자신 없는 편이다", "전혀 자신 없다", "은퇴계획이 없다", "잘 모르겠다"],
        vulnerability_targets=["retirement_planning_confidence"],
        target_context="retirement_planning_confidence",
        selection_hints=["income_gap_months_positive", "shortfall_monthly_positive"],
        dashboard_effect={"priority_cards": ["retirement_explanation_style"], "reinforced_sections": ["연금흐름 설명 방식", "행동 카드"], "summary": "연금흐름 설명 방식과 행동 카드를 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC04",
        source="financial_confidence",
        category="goal_execution_confidence",
        text_ko="재무 목표를 세운다면 달성할 자신이 있나요?",
        response_scale="single_choice",
        options=["전혀 자신 없다", "별로 자신 없다", "어느 정도 자신 있다", "매우 자신 있다", "잘 모르겠다"],
        vulnerability_targets=["goal_execution_confidence"],
        target_context="goal_execution_confidence",
        selection_hints=["shortfall_monthly_positive", "additional_savings_needed", "action_plan_needed"],
        dashboard_effect={"priority_cards": ["action_steps"], "reinforced_sections": ["체크리스트 개수", "실행 단계"], "summary": "체크리스트 개수와 실행 단계를 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC05",
        source="financial_confidence",
        category="emergency_fund_confidence",
        text_ko="한 달 안에 긴급자금을 마련할 자신이 있나요?",
        response_scale="single_choice",
        options=["확실히 마련할 수 있다", "아마 마련할 수 있다", "아마 마련하지 못할 것 같다", "확실히 마련하지 못한다", "잘 모르겠다"],
        vulnerability_targets=["emergency_fund_confidence"],
        target_context="emergency_fund_confidence",
        selection_hints=["low_liquid_assets", "income_gap_months_positive"],
        dashboard_effect={"priority_cards": ["emergency_fund"], "reinforced_sections": ["비상금 카드 설명 톤"], "summary": "비상금 카드 설명 톤을 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC06",
        source="financial_confidence",
        category="financial_avoidance_pressure",
        text_ko="현재 재정상태를 확인하면 부담되어 피하고 싶은 편인가요?",
        response_scale="single_choice",
        options=["전혀 아니다", "아니다", "보통이다", "그렇다", "매우 그렇다"],
        vulnerability_targets=["financial_avoidance_pressure"],
        target_context="financial_avoidance_pressure",
        selection_hints=["cashflow_pressure", "shortfall_monthly_positive", "financial_confidence_low"],
        dashboard_effect={"priority_cards": ["one_line_summary"], "reinforced_sections": ["한 줄 요약", "단계별 펼쳐보기"], "summary": "한 줄 요약과 단계별 펼쳐보기를 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC07",
        source="financial_confidence",
        category="explanation_preference",
        text_ko="금융 결과를 볼 때 어떤 방식이 가장 이해하기 쉬우신가요?",
        response_scale="single_choice",
        options=["쉬운 말로 짧게", "숫자와 그래프 중심", "월 금액 중심", "행동 체크리스트 중심", "가족/상담사에게 보여줄 요약본"],
        vulnerability_targets=["explanation_preference"],
        target_context="explanation_preference",
        selection_hints=["high_value_default"],
        dashboard_effect={"priority_cards": ["dashboard_presentation"], "reinforced_sections": ["대시보드 표현 방식"], "summary": "대시보드 표현 방식을 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC08",
        source="financial_confidence",
        category="shared_summary_need",
        text_ko="이 결과를 가족이나 상담사에게 보여줄 수 있는 요약본이 필요하신가요?",
        response_scale="single_choice",
        options=["필요하다", "있으면 좋겠다", "잘 모르겠다", "필요 없다"],
        vulnerability_targets=["shared_summary_need"],
        target_context="shared_summary_need",
        selection_hints=["financial_confidence_low", "family_managed", "age_50_plus", "product_complexity_high"],
        dashboard_effect={"priority_cards": ["shared_summary"], "reinforced_sections": ["가족/상담사용 요약"], "summary": "가족/상담사용 요약 제공 여부를 조정합니다."},
    ),
    QuestionPoolItem(
        id="FC09",
        source="financial_confidence",
        category="shortfall_action_confidence",
        text_ko="은퇴 후 부족액이 생긴다면, 선택한 보완 방법을 실제로 실행할 자신이 있나요?",
        response_scale="single_choice",
        options=["실행할 수 있다", "어느 정도 가능하다", "잘 모르겠다", "어렵다", "혼자서는 어렵다"],
        vulnerability_targets=["shortfall_action_confidence"],
        target_context="shortfall_action_confidence",
        selection_hints=["shortfall_monthly_positive", "retirement_shortfall_response_known"],
        dashboard_effect={"priority_cards": ["action_plan_difficulty"], "reinforced_sections": ["행동계획 난이도"], "summary": "행동계획 난이도를 조정합니다."},
    ),
]


ADAPTIVE_QUESTION_POOL: list[QuestionPoolItem] = [
    *SERVICE_QUESTION_BANK,
    *CFPB_10_QUESTIONS,
    *FINANCIAL_LITERACY_QUESTIONS,
]


@dataclass(frozen=True)
class SelectedQuestionTodo:
    """Question Selection Agent가 최종적으로 내려줘야 하는 출력 구조 TODO."""
    question: QuestionPoolItem
    reason: str
    vulnerability_to_validate: str


def select_adaptive_questions_todo(features: dict, question_pool: list[QuestionPoolItem] | None = None) -> list[SelectedQuestionTodo]:
    """TODO: 사용자 feature와 계산 결과를 보고 질문 Pool에서 정확히 5개를 선택한다.

    Intended inputs:
      - profile/user features: age, employment_status, household_size, job_type
      - calculated metrics: net_cashflow_monthly, liquid_asset_total,
        PensionReplacementRate, survival_months_at_retirement, income_gap_years,
        dsr_retire, shortfall_monthly
      - product data: pensions/accounts/loans/investments presence

    Selection sketch:
      - 50대 이상 + 개인연금 없음 -> QF9 또는 CFPB_02
      - 월 잉여현금흐름 낮음 -> QF11 또는 CFPB_08
      - 유동자산 적음 -> QF4 또는 QF13
      - 대출상환 부담 높음 -> QF2_4 또는 CFPB_09
      - 금융앱 사용 흔적 낮음 -> QP9_1 또는 QP9_8
      - 연금 종류가 여러 개인데 이해도 불명확 -> QF1_A
      - 객관 위험은 낮지만 불안 가능 -> QS3_7 또는 CFPB_10
      - 객관 위험은 높지만 과신 가능 -> QF9 또는 CFPB_02

    TODO implementation rules:
      1. Never create new question text.
      2. Select from ADAPTIVE_QUESTION_POOL only.
      3. Return exactly 5 questions.
      4. Include reason and vulnerability_to_validate for each selected question.
      5. Keep CFPB official scoring separate: if the final 5 are not the official
         abbreviated CFPB set q3/q5/q6/q8/q10, do not call it an official CFPB score.
    """
    _ = features
    _ = question_pool or ADAPTIVE_QUESTION_POOL
    return []
